fedora:
  url: http://localhost:8080/fedora/
  username: fedoraAdmin
  password: fedoraAdmin
regenerator:
  url: http://localhost:9111/islandora-1x-gatekeeper/process/pid/
  batch_size: 10
  delay_seconds: 30
  max_queue_size: 100
queue_monitor:
  host: http://localhost:8161
  username: admin
  password: admin
  queue_name: fedora
